export type Props = {
  autoComplete?: 'off' | string,
  autoFocus?: boolean,
  cols?: number,
  disabled?: boolean,
  label: string,
  minLength?: number,
  maxLength?: number,
  name: string,
  onBlur?: (params:any)=>any,
  onChange?: (params:any)=>any,
  onFocus?: (params:any)=>any,
  onInput?: (params:any)=>any,
  onKeyDown?: (params:any)=>any,
  onKeyUp?: (params:any)=>any,
  onKeyPress?: (params:any)=>any,
  password?: boolean,
  pattern?: string,
  placeholder?: string,
  readOnly?: boolean,
  reff?: any,
  required?: boolean,
  rows?: number,
  resize?: 'both'|'none'|'horizontal'|'vertical',
  margin?: string,
  size?: string,
  error?: any,
  value: string
}
