export type Props = {
  children: React.ReactNode | string,
  inline?: boolean,
  margin?: string,
  size?: string,
  color?: string,
  light?: boolean,
  bold?: boolean,
  upper?: boolean,
  tac?: boolean,
  taj?: boolean,
  primaryColor?: boolean,
  indent?: boolean,
  error?: boolean,
}
